# .github/workflows/dbt-ci.yml
name: CI

on:
  push:
    branches:
      - main
    workflow_dispatch:

env:
  PYTHON_VERSION: '3.12.1'
  PROJECT_DIR: "workshop-airflow-dbt"

jobs:
  dbt-build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      # - name: Setup Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.12.1'

      - name: Setup environment
        run: |
          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"

          # Go to project directory
          cd ~/data-projects/${{ env.PROJECT_DIR }}

          # Validating Python version
          python --version

          # Activating virtual environment
          source .venv/bin/activate
          pip install --upgrade pip
          pip install --no-cache-dir dbt-core==1.9.4 dbt-postgres==1.9.0 dbt-redshift==1.9.0

      - name: Configure dbt profile
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOF
          jornada_dw:
            outputs:
              prod:
                database: ${{ secrets.REDSHIFT_DB_NAME }}
                host: ${{ secrets.REDSHIFT_DB_HOST }}
                method: database
                pass: ${{ secrets.REDSHIFT_DB_PASS }}
                port: ${{ secrets.REDSHIFT_DB_PORT }}
                ra3_node: true
                schema: public
                threads: 16
                type: redshift
                user: ${{ secrets.REDSHIFT_DB_USER }}   
            target: prod    
          EOF

      - name: Run dbt
        working-directory: jornada_dw
        run: |
          # Ativating virtual environment
          source ~/data-projects/${{ env.PROJECT_DIR }}/.venv/bin/activate

          # Validating versions
          echo "Python: $(python --version)"
          echo "dbt: $(dbt --version)"

          # Running dbt commands
          dbt deps --profiles-dir ~/.dbt
          dbt build --profiles-dir ~/.dbt
